//! Internal `package.xml` helpers — Phase 212.G (CLI verb removed).
//!
//! Renders a `package.xml` from a component package's `Cargo.toml`
//! `[package.metadata.ament]` table, or from a bringup package's
//! `system.toml.[[component]]` block. The `nros emit package-xml`
//! user-facing verb was retired (users hand-write `package.xml` when
//! they need ament/colcon interop, or skip it entirely when they use
//! `nros launch`). The render path stays as an internal helper:
//!
//!   * `migrate::run` regenerates `package.xml` for every component
//!     during the pre-212 → post-212 sweep.
//!   * `check::run` uses [`check_drift`] to detect a hand-edited
//!     `package.xml` whose generator marker disagrees with the current
//!     `Cargo.toml` / `system.toml` (Phase 212.G.2).
//!
//! Nothing in this module is reachable from the CLI dispatcher.
//!
//! Two pkg shapes, dispatched by the artifacts present in `<pkg-dir>`:
//!
//! * **Component pkg** — `Cargo.toml` present, with
//!   `[package.metadata.nros.component]` (or `…components.<Name>`) and
//!   `[package.metadata.ament]`. Output carries `<build_depend>`,
//!   `<exec_depend>`, `<test_depend>`, and `<export><build_type>…</build_type></export>`.
//! * **Bringup pkg** — `system.toml` present. Output carries one
//!   `<exec_depend>` per `[system.components[*].pkg`, plus `<name>`/`<description>`
//!   derived from `[system].name`.
//!
//! Output discipline (every contract in §212.G):
//!
//! 1. A generated marker comment at the top so `nros check` can detect
//!    hand-edit drift later (§212.G.2 — implemented as a small `nros check`
//!    helper below; full lint surface is its own follow-up).
//! 2. Byte-identical idempotency on re-run with unchanged inputs.
//! 3. Alphabetised dependency entries so list ordering doesn't drift between
//!    `Cargo.toml` edits and emitted output.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use eyre::{Context, Result, bail};
use serde::Deserialize;

use crate::orchestration::ament::parse_ament_metadata;
use crate::orchestration::cargo_metadata_schema::{
    AmentMaintainer, PackageMetadataAment, PackageMetadataNros, SystemComponentEntry, SystemToml,
};

/// Sentinel header injected at the top of every emitted `package.xml`.
///
/// `nros check` uses substring presence of this comment to decide a
/// `package.xml` is generator-owned (and therefore eligible for drift
/// diagnostics). Keep it stable — touching the wording invalidates every
/// previously-emitted file.
pub const GENERATED_HEADER_COMMENT: &str =
    "<!-- generated by nros emit package-xml; edits will be overwritten -->";

const DEFAULT_VERSION: &str = "0.0.0";
const DEFAULT_LICENSE: &str = "Apache-2.0";
const DEFAULT_MAINTAINER_EMAIL: &str = "dev@example.com";
const DEFAULT_MAINTAINER_NAME: &str = "Developer";
const DEFAULT_BUILD_TYPE_COMPONENT: &str = "ament_cargo";
const DEFAULT_BUILD_TYPE_BRINGUP: &str = "ament_cmake";
const DEFAULT_DESCRIPTION_BRINGUP_FMT: &str = "Generated bringup package for ";

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

/// Decide which shape `<pkg-dir>` is and render the corresponding XML.
///
/// Order matters: a bringup pkg might end up in a cargo workspace's `src/`
/// tree with no `Cargo.toml` of its own; `system.toml` is the disambiguator.
pub fn render_for_pkg(pkg_dir: &Path) -> Result<String> {
    if !pkg_dir.exists() {
        bail!("pkg dir does not exist: {}", pkg_dir.display());
    }
    let cargo_toml = pkg_dir.join("Cargo.toml");
    let system_toml = pkg_dir.join("system.toml");

    if system_toml.exists() {
        return render_bringup(&system_toml);
    }
    if cargo_toml.exists() {
        return render_component(&cargo_toml);
    }
    bail!(
        "{}: neither Cargo.toml nor system.toml found — not a component or bringup pkg",
        pkg_dir.display()
    );
}

// ---------------------------------------------------------------------------
// Component pkg path
// ---------------------------------------------------------------------------

/// Minimal `Cargo.toml` projection — we only need `[package]` + the two
/// `[package.metadata.*]` tables. Everything else is opaque so `cargo`'s own
/// fields don't fight `deny_unknown_fields` discipline elsewhere in the tree.
#[derive(Debug, Deserialize)]
struct CargoManifest {
    package: CargoPackage,
}

#[derive(Debug, Deserialize)]
struct CargoPackage {
    name: String,
    #[serde(default)]
    version: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    license: Option<String>,
    #[serde(default)]
    metadata: Option<CargoPackageMetadata>,
}

#[derive(Debug, Deserialize)]
struct CargoPackageMetadata {
    #[serde(default)]
    nros: Option<PackageMetadataNros>,
    #[serde(default)]
    ament: Option<PackageMetadataAment>,
}

fn render_component(cargo_toml: &Path) -> Result<String> {
    let raw = std::fs::read_to_string(cargo_toml)
        .with_context(|| format!("read {}", cargo_toml.display()))?;
    let manifest: CargoManifest =
        toml::from_str(&raw).with_context(|| format!("parse {}", cargo_toml.display()))?;

    // Validate the nros table early — surfaces the
    // "both component and components" diagnostic from the schema layer.
    if let Some(meta) = manifest.package.metadata.as_ref()
        && let Some(nros) = meta.nros.as_ref()
    {
        nros.validate()
            .map_err(|m| eyre::eyre!("{}: {m}", cargo_toml.display()))?;
    }

    let ament = manifest
        .package
        .metadata
        .as_ref()
        .and_then(|m| m.ament.as_ref())
        .cloned()
        .unwrap_or_default();

    let pkg_name = manifest.package.name;
    let version = manifest
        .package
        .version
        .unwrap_or_else(|| DEFAULT_VERSION.into());
    // Phase 212.B.4 — `[package.metadata.ament]` is the source of
    // truth for description / license / maintainer. Cargo's
    // `[package].description` / `[package].license` are kept as
    // fallbacks (most users author them anyway); the synthesised
    // default lands only when neither is present.
    let description = ament
        .description
        .clone()
        .or(manifest.package.description)
        .unwrap_or_else(|| format!("nano-ros component package {pkg_name}"));
    let license = ament
        .license
        .clone()
        .or(manifest.package.license)
        .unwrap_or_else(|| DEFAULT_LICENSE.into());
    let build_type = ament
        .build_type
        .clone()
        .unwrap_or_else(|| DEFAULT_BUILD_TYPE_COMPONENT.into());
    let maintainer = ament.maintainer.clone();

    Ok(render_xml(RenderInputs {
        pkg_name: &pkg_name,
        version: &version,
        description: &description,
        license: &license,
        maintainer: maintainer.as_ref(),
        build_depend: sorted_unique(&ament.build_depend),
        buildtool_depend: sorted_unique(&ament.buildtool_depend),
        exec_depend: sorted_unique(&ament.exec_depend),
        test_depend: sorted_unique(&ament.test_depend),
        build_type: &build_type,
    }))
}

/// Phase 212.B.4 — convenience helper for callers that already have a
/// pkg dir and want the parsed `[package.metadata.ament]` table
/// without re-reading the manifest. Delegates to
/// [`crate::orchestration::ament::parse_ament_metadata`].
pub fn parse_pkg_ament_metadata(pkg_dir: &Path) -> Result<PackageMetadataAment> {
    parse_ament_metadata(pkg_dir)
}

// ---------------------------------------------------------------------------
// Bringup pkg path
// ---------------------------------------------------------------------------

// Phase 212.J.5 policy — the generated bringup `package.xml` deliberately
// does NOT emit `<buildtool_depend>ament_cmake</buildtool_depend>`. The
// canonical desktop launcher (`nros launch`) reads `launch/*.launch.xml`
// straight from the bringup pkg's source tree, not from an ament install
// `share/<pkg>/launch/` path, so a colcon outer build is never required
// to exercise a workspace. Users who want stock `ros2 launch <bringup>`
// compatibility add `<buildtool_depend>ament_cmake</buildtool_depend>`
// themselves (the emit is generator-owned; the drift checker only
// rejects edits to the marker-bearing region). See
// `docs/design/multi-node-workspace-layout.md` §11.1 in the nano-ros
// tree for the policy + rationale.
fn render_bringup(system_toml: &Path) -> Result<String> {
    let raw = std::fs::read_to_string(system_toml)
        .with_context(|| format!("read {}", system_toml.display()))?;
    let system: SystemToml =
        toml::from_str(&raw).with_context(|| format!("parse {}", system_toml.display()))?;

    // Bringup pkg name convention is `<system>_bringup`. Per the design doc
    // we name the emitted `<package><name>` by suffixing if missing — but the
    // user-authored `[system].name` is the source of truth either way.
    let system_name = system.system.name.clone();
    let pkg_name = if system_name.ends_with("_bringup") {
        system_name.clone()
    } else {
        format!("{system_name}_bringup")
    };
    let description = format!("{DEFAULT_DESCRIPTION_BRINGUP_FMT}{system_name}");
    let exec_depend = sorted_unique(&component_pkg_names(&system.components));

    Ok(render_xml(RenderInputs {
        pkg_name: &pkg_name,
        version: DEFAULT_VERSION,
        description: &description,
        license: DEFAULT_LICENSE,
        maintainer: None,
        build_depend: Vec::new(),
        buildtool_depend: Vec::new(),
        exec_depend,
        test_depend: Vec::new(),
        build_type: DEFAULT_BUILD_TYPE_BRINGUP,
    }))
}

fn component_pkg_names(components: &[SystemComponentEntry]) -> Vec<String> {
    components.iter().map(|c| c.pkg.clone()).collect()
}

// ---------------------------------------------------------------------------
// Hand-rolled XML emitter
// ---------------------------------------------------------------------------

struct RenderInputs<'a> {
    pkg_name: &'a str,
    version: &'a str,
    description: &'a str,
    license: &'a str,
    /// Phase 212.B.4 — when present, replaces the default
    /// `Developer <dev@example.com>` placeholder maintainer.
    maintainer: Option<&'a AmentMaintainer>,
    build_depend: Vec<String>,
    /// Phase 212.B.4 — explicit `<buildtool_depend>` rows.
    buildtool_depend: Vec<String>,
    exec_depend: Vec<String>,
    test_depend: Vec<String>,
    build_type: &'a str,
}

fn render_xml(inp: RenderInputs<'_>) -> String {
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\"?>\n");
    out.push_str(GENERATED_HEADER_COMMENT);
    out.push('\n');
    out.push_str("<package format=\"3\">\n");
    push_text_elem(&mut out, "name", inp.pkg_name, 2);
    push_text_elem(&mut out, "version", inp.version, 2);
    push_text_elem(&mut out, "description", inp.description, 2);
    push_maintainer(&mut out, 2, inp.maintainer);
    push_text_elem(&mut out, "license", inp.license, 2);

    if !inp.buildtool_depend.is_empty() {
        out.push('\n');
        for d in &inp.buildtool_depend {
            push_text_elem(&mut out, "buildtool_depend", d, 2);
        }
    }
    if !inp.build_depend.is_empty() {
        out.push('\n');
        for d in &inp.build_depend {
            push_text_elem(&mut out, "build_depend", d, 2);
        }
    }
    if !inp.exec_depend.is_empty() {
        out.push('\n');
        for d in &inp.exec_depend {
            push_text_elem(&mut out, "exec_depend", d, 2);
        }
    }
    if !inp.test_depend.is_empty() {
        out.push('\n');
        for d in &inp.test_depend {
            push_text_elem(&mut out, "test_depend", d, 2);
        }
    }

    out.push('\n');
    out.push_str("  <export>\n");
    push_text_elem(&mut out, "build_type", inp.build_type, 4);
    out.push_str("  </export>\n");
    out.push_str("</package>\n");
    out
}

fn push_maintainer(out: &mut String, indent: usize, m: Option<&AmentMaintainer>) {
    for _ in 0..indent {
        out.push(' ');
    }
    let (name, email) = match m {
        Some(m) => (m.name.as_str(), m.email.as_str()),
        None => (DEFAULT_MAINTAINER_NAME, DEFAULT_MAINTAINER_EMAIL),
    };
    out.push_str("<maintainer email=\"");
    push_attr_escaped(out, email);
    out.push_str("\">");
    push_text_escaped(out, name);
    out.push_str("</maintainer>\n");
}

fn push_text_elem(out: &mut String, tag: &str, body: &str, indent: usize) {
    for _ in 0..indent {
        out.push(' ');
    }
    out.push('<');
    out.push_str(tag);
    out.push('>');
    push_text_escaped(out, body);
    out.push_str("</");
    out.push_str(tag);
    out.push_str(">\n");
}

fn push_text_escaped(out: &mut String, body: &str) {
    for ch in body.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            _ => out.push(ch),
        }
    }
}

fn push_attr_escaped(out: &mut String, body: &str) {
    for ch in body.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(ch),
        }
    }
}

fn sorted_unique(src: &[String]) -> Vec<String> {
    let set: BTreeSet<&String> = src.iter().collect();
    set.into_iter().cloned().collect()
}

// ---------------------------------------------------------------------------
// Drift detection helper for `nros check`
// ---------------------------------------------------------------------------

/// Phase 212.G.2 drift check. Re-renders `package.xml` for the given pkg dir
/// and compares it against the existing file (if present + generator-owned).
///
/// Returns:
/// * `Ok(None)` — file absent, or carries no generated marker (hand-written
///   package.xml — out of scope for drift; user owns it).
/// * `Ok(Some(())) ` — file matches a fresh emit. No drift.
/// * `Err(_)` — file carries the marker but DIFFERS from a fresh emit:
///   the diagnostic body describes the drift. Caller (`nros check`) prints
///   it as a warning.
pub fn check_drift(pkg_dir: &Path) -> Result<DriftStatus> {
    let on_disk_path = pkg_dir.join("package.xml");
    if !on_disk_path.exists() {
        return Ok(DriftStatus::Absent);
    }
    let on_disk = std::fs::read_to_string(&on_disk_path)
        .with_context(|| format!("read {}", on_disk_path.display()))?;
    if !on_disk.contains(GENERATED_HEADER_COMMENT) {
        return Ok(DriftStatus::HandWritten);
    }
    let fresh = render_for_pkg(pkg_dir)?;
    if on_disk == fresh {
        Ok(DriftStatus::Clean)
    } else {
        Ok(DriftStatus::Drift { on_disk_path })
    }
}

#[derive(Debug)]
pub enum DriftStatus {
    /// No `package.xml` on disk.
    Absent,
    /// Present but without the generated marker — user-maintained.
    HandWritten,
    /// Present, generator-owned, and matches a fresh emit.
    Clean,
    /// Present, generator-owned, but differs from a fresh emit.
    Drift { on_disk_path: PathBuf },
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn write_file(dir: &Path, name: &str, body: &str) {
        std::fs::write(dir.join(name), body).expect("write fixture file");
    }

    fn tempdir() -> tempfile_lite::TempDir {
        tempfile_lite::TempDir::new().expect("mkdir tempdir")
    }

    #[test]
    fn emit_package_xml_for_component_pkg_from_cargo_ament_metadata() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "talker_pkg"
version = "0.2.1"
description = "Talker component for the demo system"
license = "Apache-2.0"

[package.metadata.nros.component]
default_namespace = "/demo"

[package.metadata.ament]
build_depend = ["rosidl_default_generators", "std_msgs"]
exec_depend  = ["std_msgs", "rosidl_default_runtime"]
test_depend  = ["ament_lint_auto"]
build_type   = "ament_cargo"
"#,
        );
        let xml = render_for_pkg(td.path()).expect("render");
        // The exact golden: header, sorted dep lists, expected fields.
        let expected = format!(
            "<?xml version=\"1.0\"?>\n{GENERATED_HEADER_COMMENT}\n\
             <package format=\"3\">\n\
             \x20\x20<name>talker_pkg</name>\n\
             \x20\x20<version>0.2.1</version>\n\
             \x20\x20<description>Talker component for the demo system</description>\n\
             \x20\x20<maintainer email=\"dev@example.com\">Developer</maintainer>\n\
             \x20\x20<license>Apache-2.0</license>\n\
             \n\
             \x20\x20<build_depend>rosidl_default_generators</build_depend>\n\
             \x20\x20<build_depend>std_msgs</build_depend>\n\
             \n\
             \x20\x20<exec_depend>rosidl_default_runtime</exec_depend>\n\
             \x20\x20<exec_depend>std_msgs</exec_depend>\n\
             \n\
             \x20\x20<test_depend>ament_lint_auto</test_depend>\n\
             \n\
             \x20\x20<export>\n\
             \x20\x20\x20\x20<build_type>ament_cargo</build_type>\n\
             \x20\x20</export>\n\
             </package>\n",
        );
        assert_eq!(xml, expected);
    }

    #[test]
    fn emit_package_xml_for_bringup_pkg_from_system_toml() {
        let td = tempdir();
        write_file(
            td.path(),
            "system.toml",
            r#"
[system]
name = "demo"
rmw = "zenoh"
domain_id = 0

[[component]]
pkg = "talker_pkg"
class = "talker_pkg::TalkerNode"
name = "talker"

[[component]]
pkg = "listener_pkg"
class = "listener_pkg::ListenerNode"
name = "listener"
"#,
        );
        let xml = render_for_pkg(td.path()).expect("render");
        let expected = format!(
            "<?xml version=\"1.0\"?>\n{GENERATED_HEADER_COMMENT}\n\
             <package format=\"3\">\n\
             \x20\x20<name>demo_bringup</name>\n\
             \x20\x20<version>0.0.0</version>\n\
             \x20\x20<description>Generated bringup package for demo</description>\n\
             \x20\x20<maintainer email=\"dev@example.com\">Developer</maintainer>\n\
             \x20\x20<license>Apache-2.0</license>\n\
             \n\
             \x20\x20<exec_depend>listener_pkg</exec_depend>\n\
             \x20\x20<exec_depend>talker_pkg</exec_depend>\n\
             \n\
             \x20\x20<export>\n\
             \x20\x20\x20\x20<build_type>ament_cmake</build_type>\n\
             \x20\x20</export>\n\
             </package>\n",
        );
        assert_eq!(xml, expected);
    }

    #[test]
    fn idempotent_emit_round_trip() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "talker_pkg"

[package.metadata.ament]
exec_depend = ["std_msgs"]
"#,
        );
        let a = render_for_pkg(td.path()).expect("first render");
        let b = render_for_pkg(td.path()).expect("second render");
        assert_eq!(a, b, "two consecutive renders must be byte-identical");
    }

    #[test]
    fn header_comment_present_in_output() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "p"
[package.metadata.ament]
"#,
        );
        let xml = render_for_pkg(td.path()).expect("render");
        assert!(
            xml.contains(GENERATED_HEADER_COMMENT),
            "header comment must be present in emitted output: {xml}"
        );
    }

    #[test]
    fn errors_when_target_dir_is_neither_component_nor_bringup() {
        let td = tempdir();
        let err = render_for_pkg(td.path()).expect_err("empty dir is not a pkg");
        let msg = format!("{err:#}");
        assert!(
            msg.contains("Cargo.toml") && msg.contains("system.toml"),
            "diagnostic must name both shapes: {msg}"
        );
    }

    #[test]
    fn deduplicates_and_sorts_dependency_lists() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "p"
[package.metadata.ament]
exec_depend = ["zzz", "aaa", "mmm", "aaa"]
"#,
        );
        let xml = render_for_pkg(td.path()).expect("render");
        let aaa = xml.find("aaa").expect("aaa present");
        let mmm = xml.find("mmm").expect("mmm present");
        let zzz = xml.find("zzz").expect("zzz present");
        assert!(aaa < mmm && mmm < zzz, "must be sorted");
        // De-dup: only one "aaa" line.
        let count_aaa = xml.matches("<exec_depend>aaa</exec_depend>").count();
        assert_eq!(count_aaa, 1, "duplicate entries must collapse");
    }

    #[test]
    fn drift_status_clean_after_write() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "p"
[package.metadata.ament]
exec_depend = ["std_msgs"]
"#,
        );
        let xml = render_for_pkg(td.path()).expect("render");
        std::fs::write(td.path().join("package.xml"), &xml).expect("write");
        match check_drift(td.path()).expect("drift check") {
            DriftStatus::Clean => {}
            other => panic!("expected Clean, got {other:?}"),
        }
    }

    #[test]
    fn drift_status_detects_hand_edit_when_marker_present() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "p"
[package.metadata.ament]
exec_depend = ["std_msgs"]
"#,
        );
        let mut xml = render_for_pkg(td.path()).expect("render");
        // Simulate a hand-edit: tweak the version field while keeping the
        // generated marker comment in place.
        xml = xml.replace("0.0.0", "9.9.9");
        std::fs::write(td.path().join("package.xml"), &xml).expect("write");
        match check_drift(td.path()).expect("drift check") {
            DriftStatus::Drift { .. } => {}
            other => panic!("expected Drift, got {other:?}"),
        }
    }

    #[test]
    fn drift_status_hand_written_when_no_marker() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "p"
[package.metadata.ament]
"#,
        );
        std::fs::write(
            td.path().join("package.xml"),
            "<?xml version=\"1.0\"?>\n<package format=\"3\"><name>p</name></package>\n",
        )
        .expect("write");
        match check_drift(td.path()).expect("drift check") {
            DriftStatus::HandWritten => {}
            other => panic!("expected HandWritten, got {other:?}"),
        }
    }

    #[test]
    fn drift_status_absent_when_no_file() {
        let td = tempdir();
        write_file(
            td.path(),
            "Cargo.toml",
            r#"
[package]
name = "p"
[package.metadata.ament]
"#,
        );
        match check_drift(td.path()).expect("drift check") {
            DriftStatus::Absent => {}
            other => panic!("expected Absent, got {other:?}"),
        }
    }

    // -----------------------------------------------------------------------
    // Tiny zero-dep tempdir shim, scoped to this module's tests so we don't
    // add a workspace-level dev-dep.
    // -----------------------------------------------------------------------
    mod tempfile_lite {
        use std::path::{Path, PathBuf};
        use std::sync::atomic::{AtomicU64, Ordering};

        static SEQ: AtomicU64 = AtomicU64::new(0);

        pub struct TempDir {
            path: PathBuf,
        }

        impl TempDir {
            pub fn new() -> std::io::Result<Self> {
                let n = SEQ.fetch_add(1, Ordering::Relaxed);
                let pid = std::process::id();
                let now = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_nanos())
                    .unwrap_or(0);
                let path = std::env::temp_dir().join(format!("nros-emit-pkgxml-{pid}-{now}-{n}"));
                std::fs::create_dir_all(&path)?;
                Ok(Self { path })
            }

            pub fn path(&self) -> &Path {
                &self.path
            }
        }

        impl Drop for TempDir {
            fn drop(&mut self) {
                let _ = std::fs::remove_dir_all(&self.path);
            }
        }
    }
}
