//! `nros explain` — human-readable rendering of a generated `nros-plan.json`.
//!
//! Phase 172.F. Reads the plan (the same artifact `nros check` validates) and
//! prints a structured walkthrough so a user can answer, without parsing JSON:
//! which launch instance maps to which component, the nodes + their endpoints
//! (topic + interface + QoS), how each parameter resolved (and from which
//! artifact), why a callback got its SchedContext, and what the scheduling
//! table contains. Read-only: it touches no runtime code or plan schema.

use std::{io::Write, path::PathBuf};

use clap::Args as ClapArgs;
use eyre::{Result, WrapErr};

use crate::orchestration::{
    plan::{NrosPlan, PlanEntity, TransportKind},
    schema::{DeadlinePolicy, InterfaceRef, ParameterValue, QosProfile, SchedClass},
};

#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Path to nros-plan.json
    #[arg(default_value = "build/nros/nros-plan.json")]
    pub plan: PathBuf,
}

pub fn run(args: Args) -> Result<()> {
    let raw = std::fs::read_to_string(&args.plan)
        .wrap_err_with(|| format!("read {}", args.plan.display()))?;
    let plan: NrosPlan = serde_json::from_str(&raw)
        .wrap_err_with(|| format!("parse nros-plan.json schema at {}", args.plan.display()))?;
    let stdout = std::io::stdout();
    render(&plan, &mut stdout.lock()).wrap_err("write explanation")?;
    Ok(())
}

/// Render the plan to `w`. Returns the first write error; on a terminal this is
/// infallible, but a piped/closed sink can fail mid-stream.
pub fn render<W: Write>(plan: &NrosPlan, w: &mut W) -> std::io::Result<()> {
    writeln!(
        w,
        "nros explain — system `{}`  (plan schema v{})",
        plan.system, plan.version
    )?;
    writeln!(w, "  generated by : {}", plan.trace.generated_by)?;
    writeln!(w, "  system config: {}", plan.trace.system_config)?;
    writeln!(w, "  launch record: {}", plan.trace.launch_record)?;
    writeln!(w)?;

    // Build target the plan compiles to.
    let b = &plan.build;
    write!(
        w,
        "Build: target={} board={} rmw={} profile={}",
        b.target, b.board, b.rmw, b.profile
    )?;
    if !b.features.is_empty() {
        write!(w, "  features=[{}]", b.features.join(", "))?;
    }
    writeln!(w)?;
    writeln!(w)?;

    // Components.
    writeln!(w, "Components ({}):", plan.components.len())?;
    for c in &plan.components {
        let cfg = c
            .component_config
            .as_deref()
            .map(|s| format!("  config={s}"))
            .unwrap_or_default();
        writeln!(
            w,
            "  {:<18} {}::{}  [{}]{}",
            c.id, c.package, c.component, c.language, cfg
        )?;
    }
    writeln!(w)?;

    // Instances: the launch-instance → component map, then each instance's
    // nodes/endpoints, resolved parameters, and scheduling bindings.
    writeln!(
        w,
        "Instances ({})   (launch instance → component):",
        plan.instances.len()
    )?;
    for inst in &plan.instances {
        writeln!(
            w,
            "  {} → {}   ns={}  exec={}::{}",
            inst.launch_name,
            inst.component,
            ns_or_root(&inst.namespace),
            inst.package,
            inst.executable
        )?;
        for rm in &inst.remaps {
            writeln!(w, "      remap: {} → {}", rm.from, rm.to)?;
        }
        for node in &inst.nodes {
            writeln!(
                w,
                "      node {}   (source: {})",
                node.resolved_name, node.source_node
            )?;
            for e in &node.entities {
                writeln!(w, "        {}", entity_line(e))?;
            }
        }
        if !inst.parameters.is_empty() {
            writeln!(w, "      parameters  (name = value  [resolved from]):")?;
            for p in &inst.parameters {
                writeln!(
                    w,
                    "        {} = {}   [{} @ {}]",
                    p.name,
                    value_str(&p.value),
                    source_kind_str(&p.source.kind),
                    p.source.artifact
                )?;
            }
        }
        if !inst.sched_bindings.is_empty() {
            writeln!(w, "      sched bindings  (callback → context):")?;
            for sb in &inst.sched_bindings {
                let prio = sb
                    .priority
                    .map(|v| format!(" prio={v}"))
                    .unwrap_or_default();
                writeln!(
                    w,
                    "        {} → {}{}   (from {})",
                    sb.callback, sb.context, prio, sb.source
                )?;
            }
        }
        writeln!(w)?;
    }

    // The scheduling table the runtime is generated against.
    if !plan.sched_contexts.is_empty() {
        writeln!(
            w,
            "SchedContexts ({})   (the generated scheduling table):",
            plan.sched_contexts.len()
        )?;
        for s in &plan.sched_contexts {
            let mut bits = vec![format!("class={}", sched_class_str(&s.class))];
            if let Some(p) = s.priority {
                bits.push(format!("prio={p}"));
            }
            if let Some(v) = s.period_ms {
                bits.push(format!("period={v}ms"));
            }
            if let Some(v) = s.budget_ms {
                bits.push(format!("budget={v}ms"));
            }
            if let Some(v) = s.deadline_ms {
                bits.push(format!(
                    "deadline={v}ms({})",
                    deadline_policy_str(&s.deadline_policy)
                ));
            }
            if let Some(v) = s.core {
                bits.push(format!("core={v}"));
            }
            if let Some(ref t) = s.task {
                bits.push(format!("task={t}"));
            }
            writeln!(
                w,
                "  {:<16} executor={}  {}",
                s.id,
                s.executor,
                bits.join(" ")
            )?;
        }
        writeln!(w)?;
    }

    // Transports (bridge mode = more than one).
    if !plan.build.transports.is_empty() {
        writeln!(w, "Transports ({}):", plan.build.transports.len())?;
        for t in &plan.build.transports {
            let id =
                t.id.as_deref()
                    .map(|s| format!(" id={s}"))
                    .unwrap_or_default();
            let detail = transport_detail(t);
            let rmw = t
                .rmw
                .as_deref()
                .map(|s| format!(" rmw={s}"))
                .unwrap_or_default();
            writeln!(w, "  {}{}{}{}", transport_kind_str(t.kind), id, detail, rmw)?;
        }
        writeln!(w)?;
    }

    // Additive sections (only present on newer plans).
    if let Some(ref lc) = plan.lifecycle {
        writeln!(w, "Lifecycle: managed node, autostart={:?}", lc.autostart)?;
    }
    if !plan.callback_chains.is_empty() {
        writeln!(
            w,
            "Callback chains: {} (dataflow-inferred)",
            plan.callback_chains.len()
        )?;
    }
    if !plan.callback_groups.is_empty() {
        writeln!(w, "Callback groups: {}", plan.callback_groups.len())?;
    }
    Ok(())
}

fn ns_or_root(ns: &str) -> &str {
    if ns.is_empty() { "/" } else { ns }
}

fn entity_line(e: &PlanEntity) -> String {
    match e {
        PlanEntity::Publisher {
            resolved_name,
            interface,
            qos,
            ..
        } => format!(
            "pub  {}  {}  [{}]",
            resolved_name,
            iface_str(interface),
            qos_str(qos)
        ),
        PlanEntity::Subscriber {
            resolved_name,
            interface,
            qos,
            callback,
            ..
        } => format!(
            "sub  {}  {}  [{}]{}",
            resolved_name,
            iface_str(interface),
            qos_str(qos),
            cb_suffix(callback)
        ),
        PlanEntity::Timer {
            period_ms,
            callback,
            ..
        } => format!("timer  {period_ms}ms{}", cb_suffix(callback)),
        PlanEntity::ServiceServer {
            resolved_name,
            interface,
            callback,
            ..
        } => format!(
            "srv-server  {}  {}{}",
            resolved_name,
            iface_str(interface),
            cb_suffix(callback)
        ),
        PlanEntity::ServiceClient {
            resolved_name,
            interface,
            ..
        } => format!("srv-client  {}  {}", resolved_name, iface_str(interface)),
        PlanEntity::ActionServer {
            resolved_name,
            interface,
            callback,
            ..
        } => format!(
            "action-server  {}  {}{}",
            resolved_name,
            iface_str(interface),
            cb_suffix(callback)
        ),
        PlanEntity::ActionClient {
            resolved_name,
            interface,
            ..
        } => format!("action-client  {}  {}", resolved_name, iface_str(interface)),
    }
}

fn cb_suffix(callback: &Option<String>) -> String {
    callback
        .as_deref()
        .map(|c| format!("  → {c}"))
        .unwrap_or_default()
}

fn iface_str(i: &InterfaceRef) -> String {
    format!("{}/{}", i.package, i.name)
}

fn qos_str(q: &QosProfile) -> String {
    format!(
        "{:?}/{:?}/{:?}({})",
        q.reliability, q.durability, q.history, q.depth
    )
}

fn value_str(v: &ParameterValue) -> String {
    match v {
        ParameterValue::Bool(b) => b.to_string(),
        ParameterValue::Integer(i) => i.to_string(),
        ParameterValue::Float(f) => f.to_string(),
        ParameterValue::String(s) => format!("\"{s}\""),
        ParameterValue::BoolArray(a) => format!("{a:?}"),
        ParameterValue::IntegerArray(a) => format!("{a:?}"),
        ParameterValue::FloatArray(a) => format!("{a:?}"),
        ParameterValue::StringArray(a) => format!("{a:?}"),
    }
}

fn source_kind_str(k: &crate::orchestration::plan::ParameterSourceKind) -> &'static str {
    use crate::orchestration::plan::ParameterSourceKind::*;
    match k {
        SourceDefault => "source default",
        ComponentConfig => "component config",
        SystemOverlay => "system overlay",
        Launch => "launch",
    }
}

fn sched_class_str(c: &SchedClass) -> &'static str {
    match c {
        SchedClass::BestEffort => "best-effort",
        SchedClass::RealTime => "real-time",
        SchedClass::TimeTriggered => "time-triggered",
        SchedClass::Interrupt => "interrupt",
    }
}

fn deadline_policy_str(p: &DeadlinePolicy) -> &'static str {
    match p {
        DeadlinePolicy::Ignore => "ignore",
        DeadlinePolicy::Warn => "warn",
        DeadlinePolicy::Skip => "skip",
        DeadlinePolicy::Fault => "fault",
    }
}

fn transport_kind_str(k: TransportKind) -> &'static str {
    match k {
        TransportKind::Ethernet => "ethernet",
        TransportKind::Wifi => "wifi",
        TransportKind::Serial => "serial",
        TransportKind::Can => "can",
    }
}

fn transport_detail(t: &crate::orchestration::plan::PlanTransport) -> String {
    let mut parts = Vec::new();
    if let Some(ref ip) = t.ip {
        parts.push(format!(" ip={ip}"));
    }
    if let Some(ref dev) = t.device {
        parts.push(format!(" device={dev}"));
    }
    if let Some(baud) = t.baudrate {
        parts.push(format!(" baud={baud}"));
    }
    parts.join("")
}
