//! Emit `$OUT_DIR/run_plan.rs` from an [`NrosPlan`].
//!
//! The emitted file is `include!`d from the Entry pkg's `main.rs`.
//! It declares one fn:
//!
//! ```ignore
//! pub fn run_plan(
//!     runtime: &mut ::nros_platform::RuntimeCtx<'_>,
//! ) -> ::core::result::Result<(), ::nros_build::RuntimeError> {
//!     // For each plan.instances entry:
//!     //   ::<pkg_ident>::register(runtime).map_err(|_|
//!     //       ::nros_platform::RuntimeError::NodeRegister("<pkg>::<exec>"))?;
//!     Ok(())
//! }
//! ```
//!
//! The fn body deliberately keeps no per-instance state — it is a
//! flat sequence of register calls in plan-order (which the planner
//! already orders so producers come before consumers). Lifecycle
//! hooks / shared-state regions / param overlays are NOT yet emitted;
//! they live in the plan and will be folded in over follow-up
//! patches.

use core::fmt::Write as _;

use nros_cli_core::orchestration::plan::NrosPlan;

/// Render the body of `$OUT_DIR/run_plan.rs` for the given plan.
///
/// Returns a UTF-8 string the caller writes verbatim. Doc-comments
/// in the emitted code spell out the lineage (planner version,
/// system name, instance count) so a curious user can introspect
/// without re-running codegen.
pub fn emit_run_plan(plan: &NrosPlan) -> String {
    let mut out = String::with_capacity(4096);
    let _ = writeln!(
        out,
        "// AUTO-GENERATED by nros-build::emit_run_plan (Phase 212.N.4)."
    );
    let _ = writeln!(out, "// DO NOT EDIT — regenerated by Entry pkg build.rs.");
    let _ = writeln!(out, "//");
    let _ = writeln!(out, "// plan.version : {}", plan.version);
    let _ = writeln!(out, "// plan.system  : {}", plan.system);
    let _ = writeln!(out, "// instance count: {}", plan.instances.len());
    out.push('\n');

    out.push_str(
        "pub fn run_plan(\n    runtime: &mut ::nros_platform::RuntimeCtx<'_>,\n) -> ::core::result::Result<(), ::nros_platform::RuntimeError> {\n    let _ = runtime; // silence unused-warn on empty plans\n",
    );

    for inst in &plan.instances {
        // Match the planner's record-side pkg field (a launch <node
        // pkg="X" exec="Y"/> → record.node.package). The plan's
        // PlanInstance carries the unsanitised pkg name; here we
        // produce the dash-stripped ident that matches Rust's
        // crate-name → ident projection (`-` → `_`).
        //
        // Phase 212.M-F.19: §212.N.7 + §212.N.12 settled the
        // register-wrapper shape on `<pkg>::register` at the crate
        // root (no nested `<exec>` module). The symbol path is
        // therefore `::<pkg_ident>::register`; the error label keeps
        // the human-readable `<pkg>::<exec>` identity used in
        // diagnostics.
        let pkg_ident = pkg_ident_from(inst);
        let pkg_label = pkg_label_from(inst);
        let _ = writeln!(
            out,
            "    ::{pkg_ident}::register(runtime).map_err(|_| ::nros_platform::RuntimeError::NodeRegister({pkg_label:?}))?;"
        );
    }

    out.push_str("    Ok(())\n}\n");
    out
}

fn pkg_ident_from(inst: &nros_cli_core::orchestration::plan::PlanInstance) -> String {
    // Phase 212.M-F.19: the Rust symbol path is `::<pkg>::register`
    // where `<pkg>` is the *crate name* (post-`-`→`_` projection).
    // Prefer the planner's `package` field (the unambiguous crate
    // name); fall back across older planner versions that only set
    // `pkg` / `name`. We explicitly do NOT fall back to `component`
    // here — post-§212.M-F.17 the planner serializes `component` as
    // the combined `"<pkg>::<exec>"` identity, which would generate
    // a non-existent `::<pkg>::<exec>::register` symbol.
    let raw = instance_field(inst, &["package", "pkg", "name"]);
    raw.replace('-', "_")
}

fn pkg_label_from(inst: &nros_cli_core::orchestration::plan::PlanInstance) -> String {
    // Diagnostics keep the `<pkg>::<exec>` human identity (so a
    // RuntimeError::NodeRegister bubble carries enough context to
    // disambiguate two executables in the same crate). The planner's
    // `component` field already carries that combined identity post-
    // §212.M-F.17; fall through to bare-pkg when older planners only
    // expose the crate name.
    let combined = instance_field(inst, &["component"]);
    if !combined.is_empty() && combined != "unknown" {
        return combined;
    }
    let pkg = instance_field(inst, &["package", "pkg", "name"]);
    let exec = instance_field(inst, &["executable", "exec"]);
    if !exec.is_empty() && exec != "unknown" && pkg != exec {
        format!("{pkg}::{exec}")
    } else {
        pkg
    }
}

fn instance_field(
    inst: &nros_cli_core::orchestration::plan::PlanInstance,
    keys: &[&str],
) -> String {
    // Round-trip through serde_json::Value so the emitter doesn't
    // require a knowledge of `PlanInstance`'s precise field layout
    // (which has churned across planner versions). Walk the keys in
    // priority order; return the first hit.
    let v = serde_json::to_value(inst).unwrap_or(serde_json::Value::Null);
    for key in keys {
        if let Some(s) = v.get(*key).and_then(|x| x.as_str()) {
            return s.to_string();
        }
    }
    "unknown".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use nros_cli_core::orchestration::plan::NrosPlan;

    /// Build a minimally-populated single-instance `NrosPlan` from JSON.
    /// Keeps the test independent of the (churn-prone) `PlanInstance`
    /// field layout — the emitter itself walks the plan via
    /// `serde_json::to_value`, so a deserialise/reserialise round-trip
    /// is the most faithful integration point.
    fn plan_with_one_instance(package: &str, executable: &str, component: &str) -> NrosPlan {
        let json = serde_json::json!({
            "version": 2,
            "system": "test_system",
            "trace": {
                "system_config": "test.toml",
                "launch_record": "test.launch.json",
                "generated_by": "nros-build-test",
            },
            "components": [],
            "instances": [{
                "id": "inst.0",
                "component": component,
                "package": package,
                "executable": executable,
                "launch_name": executable,
                "namespace": "/",
                "kind": "node",
                "remaps": [],
                "env": [],
                "nodes": [],
                "callbacks": [],
                "parameters": [],
                "sched_bindings": [],
                "trace": {
                    "launch_record_entity": "node.0",
                    "source_metadata": "src.json",
                },
            }],
            "interfaces": [],
            "sched_contexts": [],
            "build": {
                "target": "x86_64-unknown-linux-gnu",
                "board": "posix",
                "rmw": "zenoh",
                "profile": "release",
                "features": [],
                "cfg": {},
            },
        });
        serde_json::from_value(json).expect("test fixture PlanInstance deserialises")
    }

    #[test]
    fn emit_uses_package_for_symbol_path_not_component() {
        // §212.M-F.19 — the buggy pre-fix output emitted
        //   ::shared_node_pkg::shared_node::register
        // because it walked `component` (= "shared_node_pkg::shared_node")
        // for the symbol path. Post-fix the symbol path is
        // `::shared_node_pkg::register` (crate-name from `package`).
        let plan = plan_with_one_instance(
            "shared_node_pkg",
            "shared_node",
            "shared_node_pkg::shared_node",
        );
        let out = emit_run_plan(&plan);
        assert!(
            out.contains("::shared_node_pkg::register(runtime)"),
            "expected `::shared_node_pkg::register(runtime)` in emitted body; got:\n{out}"
        );
        assert!(
            !out.contains("::shared_node_pkg::shared_node::register"),
            "must NOT emit the buggy nested-exec symbol path; got:\n{out}"
        );
    }

    #[test]
    fn emit_uses_node_register_variant_not_component_register() {
        // §212.N.12 renamed RuntimeError::ComponentRegister →
        // RuntimeError::NodeRegister.
        let plan = plan_with_one_instance("demo_pkg", "demo", "demo_pkg::demo");
        let out = emit_run_plan(&plan);
        assert!(
            out.contains("RuntimeError::NodeRegister("),
            "expected `RuntimeError::NodeRegister(` in emitted body; got:\n{out}"
        );
        assert!(
            !out.contains("RuntimeError::ComponentRegister"),
            "must NOT emit the pre-rename `ComponentRegister` variant; got:\n{out}"
        );
    }

    #[test]
    fn emit_keeps_pkg_exec_label_for_diagnostics() {
        // The error-context arg keeps the human-readable
        // `<pkg>::<exec>` identity (M-F.19 fix item 4).
        let plan = plan_with_one_instance(
            "shared_node_pkg",
            "shared_node",
            "shared_node_pkg::shared_node",
        );
        let out = emit_run_plan(&plan);
        assert!(
            out.contains("\"shared_node_pkg::shared_node\""),
            "expected error label `\"shared_node_pkg::shared_node\"` in emitted body; got:\n{out}"
        );
    }

    #[test]
    fn emit_projects_dashes_to_underscores_in_symbol_path() {
        // Rust crate-name → ident projection: `-` → `_`.
        let plan = plan_with_one_instance("my-pkg", "my-exec", "my-pkg::my-exec");
        let out = emit_run_plan(&plan);
        assert!(
            out.contains("::my_pkg::register(runtime)"),
            "expected dash-stripped `::my_pkg::register`; got:\n{out}"
        );
        // Label keeps the original (unstripped) identity for diagnostics.
        assert!(
            out.contains("\"my-pkg::my-exec\""),
            "expected raw `\"my-pkg::my-exec\"` label preserved; got:\n{out}"
        );
    }

    #[test]
    fn emit_golden_single_instance_shape() {
        // Pin the full per-instance emit line so a future template
        // shift breaks this test (and forces a roadmap entry rather
        // than silent drift).
        let plan = plan_with_one_instance(
            "shared_node_pkg",
            "shared_node",
            "shared_node_pkg::shared_node",
        );
        let out = emit_run_plan(&plan);
        let expected = "    ::shared_node_pkg::register(runtime).map_err(|_| ::nros_platform::RuntimeError::NodeRegister(\"shared_node_pkg::shared_node\"))?;";
        assert!(
            out.contains(expected),
            "expected golden line:\n{expected}\n\nin emitted body:\n{out}"
        );
    }

    #[test]
    fn emit_empty_plan_keeps_no_register_calls() {
        let json = serde_json::json!({
            "version": 2,
            "system": "empty_system",
            "trace": {
                "system_config": "x",
                "launch_record": "y",
                "generated_by": "z",
            },
            "components": [],
            "instances": [],
            "interfaces": [],
            "sched_contexts": [],
            "build": {
                "target": "x86_64-unknown-linux-gnu",
                "board": "posix",
                "rmw": "zenoh",
                "profile": "release",
                "features": [],
                "cfg": {},
            },
        });
        let plan: NrosPlan = serde_json::from_value(json).unwrap();
        let out = emit_run_plan(&plan);
        assert!(!out.contains("::register(runtime)"));
        assert!(out.contains("pub fn run_plan("));
        assert!(out.contains("Ok(())\n}"));
    }
}
