//! Emit `$OUT_DIR/run_plan.rs` from an [`NrosPlan`].
//!
//! The emitted file is `include!`d from the Entry pkg's `main.rs`.
//! It declares one fn:
//!
//! ```ignore
//! pub fn run_plan(
//!     runtime: &mut ::nros_platform::RuntimeCtx<'_>,
//! ) -> ::core::result::Result<(), ::nros_build::RuntimeError> {
//!     // For each plan.instances entry:
//!     //   ::<pkg_ident>::register(runtime).map_err(|_|
//!     //       ::nros_build::RuntimeError::ComponentRegister("<pkg>"))?;
//!     Ok(())
//! }
//! ```
//!
//! The fn body deliberately keeps no per-instance state — it is a
//! flat sequence of register calls in plan-order (which the planner
//! already orders so producers come before consumers). Lifecycle
//! hooks / shared-state regions / param overlays are NOT yet emitted;
//! they live in the plan and will be folded in over follow-up
//! patches.

use core::fmt::Write as _;

use nros_cli_core::orchestration::plan::NrosPlan;

/// Render the body of `$OUT_DIR/run_plan.rs` for the given plan.
///
/// Returns a UTF-8 string the caller writes verbatim. Doc-comments
/// in the emitted code spell out the lineage (planner version,
/// system name, instance count) so a curious user can introspect
/// without re-running codegen.
pub fn emit_run_plan(plan: &NrosPlan) -> String {
    let mut out = String::with_capacity(4096);
    let _ = writeln!(
        out,
        "// AUTO-GENERATED by nros-build::emit_run_plan (Phase 212.N.4)."
    );
    let _ = writeln!(out, "// DO NOT EDIT — regenerated by Entry pkg build.rs.");
    let _ = writeln!(out, "//");
    let _ = writeln!(out, "// plan.version : {}", plan.version);
    let _ = writeln!(out, "// plan.system  : {}", plan.system);
    let _ = writeln!(out, "// instance count: {}", plan.instances.len());
    out.push('\n');

    out.push_str(
        "pub fn run_plan(\n    runtime: &mut ::nros_platform::RuntimeCtx<'_>,\n) -> ::core::result::Result<(), ::nros_platform::RuntimeError> {\n    let _ = runtime; // silence unused-warn on empty plans\n",
    );

    for inst in &plan.instances {
        // Match the planner's record-side pkg field (a launch <node
        // pkg="X" exec="Y"/> → record.node.package). The plan's
        // PlanInstance carries the unsanitised pkg name; here we
        // produce the dash-stripped ident that matches Rust's
        // crate-name → ident projection (`-` → `_`).
        let pkg_ident = pkg_ident_from(inst);
        let pkg_label = pkg_label_from(inst);
        let _ = writeln!(
            out,
            "    ::{pkg_ident}::register(runtime).map_err(|_| ::nros_platform::RuntimeError::ComponentRegister({pkg_label:?}))?;"
        );
    }

    out.push_str("    Ok(())\n}\n");
    out
}

fn pkg_ident_from(inst: &nros_cli_core::orchestration::plan::PlanInstance) -> String {
    // The plan's `PlanInstance` carries `component` (= component-pkg
    // name) — use whatever serde_json field actually exists. We
    // accept either `component` or `pkg` to stay compatible across
    // planner versions. Convert dashes → underscores for the Rust
    // ident.
    let raw = instance_pkg_name(inst);
    raw.replace('-', "_")
}

fn pkg_label_from(inst: &nros_cli_core::orchestration::plan::PlanInstance) -> String {
    instance_pkg_name(inst)
}

fn instance_pkg_name(inst: &nros_cli_core::orchestration::plan::PlanInstance) -> String {
    // Round-trip through serde_json::Value so the emitter doesn't
    // require a knowledge of `PlanInstance`'s precise field layout
    // (which has churned across planner versions). The planner emits
    // one of `pkg` / `component` / `name`; we walk those in priority
    // order.
    let v = serde_json::to_value(inst).unwrap_or(serde_json::Value::Null);
    for key in ["component", "pkg", "package", "name"] {
        if let Some(s) = v.get(key).and_then(|x| x.as_str()) {
            return s.to_string();
        }
    }
    "unknown".to_string()
}
